// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/file-storage.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "fileStorage";

/** Single file upload messages (existing) */
export interface SingleUploadFileRequest {
  path: string;
  filename: string;
  fileData: Uint8Array;
  mimetype: string;
}

export interface SingleUploadFileResponse {
  filename: string;
  url: string;
}

/** Multiple files with individual paths */
export interface MultipleUploadFileRequest {
  files: FileUpload[];
}

export interface FileUpload {
  path: string;
  filename: string;
  fileData: Uint8Array;
  mimetype: string;
}

export interface MultipleUploadFileResponse {
  files: UploadedFile[];
}

export interface UploadedFile {
  filename: string;
  url: string;
}

export const FILE_STORAGE_PACKAGE_NAME = "fileStorage";

export interface FileStorageServiceClient {
  singleUpload(request: SingleUploadFileRequest, metadata: Metadata): Observable<SingleUploadFileResponse>;

  multipleUpload(request: MultipleUploadFileRequest, metadata: Metadata): Observable<MultipleUploadFileResponse>;
}

export interface FileStorageServiceController {
  singleUpload(
    request: SingleUploadFileRequest,
  ): Promise<SingleUploadFileResponse> | Observable<SingleUploadFileResponse> | SingleUploadFileResponse;

  multipleUpload(
    request: MultipleUploadFileRequest,
  ): Promise<MultipleUploadFileResponse> | Observable<MultipleUploadFileResponse> | MultipleUploadFileResponse;
}

export function FileStorageServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["singleUpload", "multipleUpload"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FileStorageService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FileStorageService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FILE_STORAGE_SERVICE_NAME = "FileStorageService";
