// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/iam.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "iam";

export interface IamAuthenticateRequest {
  token: string;
}

/** Message equivalent of ActiveUserData */
export interface ActiveUserData {
  sub: string;
  email: string;
  role: string;
  /** optional field (empty string if not set) */
  refreshTokenId?: string | undefined;
}

/** Message equivalent of IamAuthenticateResponse */
export interface IamAuthenticateResponse {
  authenticated: boolean;
  payload: ActiveUserData | undefined;
}

export const IAM_PACKAGE_NAME = "iam";

export interface IamServiceClient {
  authenticate(request: IamAuthenticateRequest): Observable<IamAuthenticateResponse>;
}

export interface IamServiceController {
  authenticate(
    request: IamAuthenticateRequest,
  ): Promise<IamAuthenticateResponse> | Observable<IamAuthenticateResponse> | IamAuthenticateResponse;
}

export function IamServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["authenticate"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("IamService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("IamService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const IAM_SERVICE_NAME = "IamService";
