// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: proto/user.proto

/* eslint-disable */
import { ActiveUserData } from '@app/common/interfaces';
import { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'user';

export interface UpdateGrpcPatientProfileRequest {
  /** Full name of the patient */
  fullname?: string | undefined;
  /** Date of birth of the patient (ISO 8601 format string) */
  dob?: string | undefined;
  photoUrl?: string | undefined;
  location?: Location | undefined;
}

/** Request message for creating a provider */
export interface UpdateGrpcProviderProfileRequest {
  /** Full name of the patient */
  fullname?: string | undefined;
  /** Date of birth of the patient (ISO 8601 format string) */
  dob?: string | undefined;
  photoUrl?: string | undefined;
  phone?: string | undefined;
}

/** Request message for creating a provider */
export interface CreateGrpcProviderProfileRequest {
  /** Patient's email address */
  email: string;
  /** Full name of the patient */
  fullname: string;
  /** Patient's gender (Male, Female, Other) */
  gender: string;
  /** Date of birth of the patient (ISO 8601 format string) */
  dob: string;
  photoUrl: string;
}

/** Request message for creating a patient */
export interface CreateGrpcPatientProfileRequest {
  /** Patient's email address */
  email: string;
  /** Full name of the patient */
  fullname: string;
  /** Patient's location details */
  location: Location | undefined;
  /** Patient's gender (Male, Female, Other) */
  gender: string;
  /** Date of birth of the patient (ISO 8601 format string) */
  dob: string;
}

/** Location details message */
export interface Location {
  /** The full country name */
  country: string;
  /** The short country code (e.g., NG) */
  shortCountry: string;
  /** The full state name */
  state: string;
  /** The short state code or abbreviation */
  shortState: string;
  /** The full city name */
  city: string;
  /** The short city code or abbreviation */
  shortCity: string;
  /** The full address string */
  address: string;
  /** The latitude coordinate as a string */
  latitude: string;
  /** The longitude coordinate as a string */
  longitude: string;
  /** The Google Maps or Place API identifier */
  placeId: string;
  /** The formatted address returned by the map service */
  formattedAddress: string;
}

export interface CreateGrpcPatientKycSubmissionRequest {
  documentType: string;
  documentNumber?: string | undefined;
  frontDocumentUri: string;
  backDocumentUri?: string | undefined;
}

export interface CreateGrpcPatientProfileResponse {
  userId: string;
}

export const USER_PACKAGE_NAME = 'user';

export interface UserServiceClient {
  createGrpcPatientProfile(
    request: CreateGrpcPatientProfileRequest,
    metadata: Metadata,
  ): Observable<CreateGrpcPatientProfileResponse>;

  createGrpcPatientKycSubmission(
    request: CreateGrpcPatientKycSubmissionRequest,
    metadata: Metadata,
  ): Observable<CreateGrpcPatientProfileResponse>;

  createGrpcProviderProfile(
    request: CreateGrpcProviderProfileRequest,
    metadata: Metadata,
  ): Observable<CreateGrpcPatientProfileResponse>;

  updateGrpcPatientProfile(
    request: UpdateGrpcPatientProfileRequest,
  ): Observable<CreateGrpcPatientProfileResponse>;

  updateGrpcProviderProfile(
    request: UpdateGrpcProviderProfileRequest,
    metadata: Metadata,
  ): Observable<CreateGrpcPatientProfileResponse>;
}

export interface UserServiceController {
  createGrpcPatientProfile(
    request: CreateGrpcPatientProfileRequest,
    activeUserData: ActiveUserData,
  ):
    | Promise<CreateGrpcPatientProfileResponse>
    | Observable<CreateGrpcPatientProfileResponse>
    | CreateGrpcPatientProfileResponse;

  createGrpcPatientKycSubmission(
    request: CreateGrpcPatientKycSubmissionRequest,
    activeUserData: ActiveUserData,
  ):
    | Promise<CreateGrpcPatientProfileResponse>
    | Observable<CreateGrpcPatientProfileResponse>
    | CreateGrpcPatientProfileResponse;

  createGrpcProviderProfile(
    request: CreateGrpcProviderProfileRequest,
    activeUserData: ActiveUserData,
  ):
    | Promise<CreateGrpcPatientProfileResponse>
    | Observable<CreateGrpcPatientProfileResponse>
    | CreateGrpcPatientProfileResponse;

  updateGrpcPatientProfile(
    request: UpdateGrpcPatientProfileRequest,
    activeUserData: ActiveUserData,
  ):
    | Promise<CreateGrpcPatientProfileResponse>
    | Observable<CreateGrpcPatientProfileResponse>
    | CreateGrpcPatientProfileResponse;

  updateGrpcProviderProfile(
    request: UpdateGrpcProviderProfileRequest,
    activeUserData: ActiveUserData,
  ):
    | Promise<CreateGrpcPatientProfileResponse>
    | Observable<CreateGrpcPatientProfileResponse>
    | CreateGrpcPatientProfileResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createGrpcPatientProfile',
      'createGrpcPatientKycSubmission',
      'createGrpcProviderProfile',
      'updateGrpcPatientProfile',
      'updateGrpcProviderProfile',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('UserService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('UserService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const USER_SERVICE_NAME = 'UserService';
